### ISSUE TITLE
Repository leaks API secrets

### ISSUE THREAD

**Issue by neon-sunset** [UncleDave/CoK-Memes#4]
https://github.com/UncleDave/CoK-Memes/blob/main/bot/src/ChampionsOfKhazad.Bot.Infrastructure/Pulumi.prod.yaml

You may want to delete the keys and rotate them ASAP.

Also a question: why are you opting into using REST transport over gRPC one here? https://github.com/UncleDave/CoK-Memes/blob/main/bot/src/ChampionsOfKhazad.Bot.Pinecone/IndexService.cs This is not the first time I see it and it would be nice to know if there is some issue or the documentation needs to be updated to explicitly call-out this.

**Comment by UncleDave** [comment]
> https://github.com/UncleDave/CoK-Memes/blob/main/bot/src/ChampionsOfKhazad.Bot.Infrastructure/Pulumi.prod.yaml
>
> You may want to delete the keys and rotate them ASAP.

These are encrypted secrets.

>Also a question: why are you opting into using REST transport over gRPC one here? https://github.com/UncleDave/CoK-Memes/blob/main/bot/src/ChampionsOfKhazad.Bot.Pinecone/IndexService.cs This is not the first time I see it and it would be nice to know if there is some issue or the documentation needs to be updated to explicitly call-out this.

I haven't used GRPC anywhere else, it seemed reasonable to just stick to REST with Pinecone, too. As far as I can see the docs don't offer any guidance for why a specific transport should be used.

Out of interest, how is it you came to arrive at this repo? Does NuGet notify you when your package is consumed by a new project?

**Comment by neon-sunset** [comment]
> I haven't used GRPC anywhere else, it seemed reasonable to just stick to REST with Pinecone, too. As far as I can see the docs don't offer any guidance for why a specific transport should be used.

I see, the biggest reason to use gRPC over REST is the former providing strong guarantee against side effects of formatting/parsing floating point integers from/to utf8 in JSON. This is not that important but I'm still surprised developers insist *against* the default exposed by the library (`.GetIndex` overload without generic argument).

> Out of interest, how is it you came to arrive at this repo? Does NuGet notify you when your package is consumed by a new project?

There is a tab "Used By" at the bottom right of the repository (it sometimes doesn't show up), so I got curious to see how the library is used, whether there are issues, etc.

**Comment by UncleDave** [comment]
I'll switch to the default GRPC transport and see how it goes 👍.

**Comment by neon-sunset** [comment]
Thank you for giving the library a try, if you have any questions or something does not work - feel free to open an issue or discussions post. Although the API secrets are encrypted, their presence in the repo gave me a good scare for a moment 😅

Cheers!
